"""Summarize where selective graph rescue can and cannot change retrieval."""

from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path


DATASET_ORDER = ("hotpot", "2wiki", "musique")
SLICE_ORDER = ("already_solved", "anchor_failure", "rescuable", "unreachable")
DISPLAY = {
    "hotpot": "HotpotQA",
    "2wiki": "2WikiMultiHopQA",
    "musique": "MuSiQue",
    "already_solved": "Already solved",
    "anchor_failure": "No support anchor",
    "rescuable": "Graph-reachable",
    "unreachable": "Graph-unreachable",
}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("outputs/final_v1/analysis/paired_outcomes.csv"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("outputs/final_v1/analysis/failure_funnel.csv"),
    )
    parser.add_argument(
        "--json-output",
        type=Path,
        default=Path("outputs/final_v1/analysis/failure_funnel.json"),
    )
    parser.add_argument(
        "--tex-output",
        type=Path,
        default=Path("outputs/jiis_submission/failure_analysis.tex"),
    )
    args = parser.parse_args()

    with args.input.open(encoding="utf-8-sig", newline="") as handle:
        source = list(csv.DictReader(handle))
    grouped: dict[tuple[str, str], list[dict]] = defaultdict(list)
    for row in source:
        grouped[(row["dataset"], row["slice"])].append(row)

    rows = []
    for dataset in DATASET_ORDER:
        for slice_name in SLICE_ORDER:
            items = grouped.get((dataset, slice_name), [])
            if not items:
                continue
            wins = sum(item["outcome"] == "win" for item in items)
            losses = sum(item["outcome"] == "loss" for item in items)
            ties = len(items) - wins - losses
            recall_delta = sum(
                float(item["support_recall_delta"]) for item in items
            ) / len(items)
            rows.append(
                {
                    "dataset": dataset,
                    "slice": slice_name,
                    "queries": len(items),
                    "share": len(items)
                    / sum(row["dataset"] == dataset for row in source),
                    "wins": wins,
                    "losses": losses,
                    "ties": ties,
                    "win_rate": wins / len(items),
                    "loss_rate": losses / len(items),
                    "mean_support_recall_delta": recall_delta,
                }
            )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    args.json_output.write_text(
        json.dumps(
            {
                "definition": {
                    "already_solved": "Hybrid context already contains all support.",
                    "anchor_failure": "Initial seeds contain no supporting passage.",
                    "rescuable": "Missing support is reachable from an initial support anchor.",
                    "unreachable": "The clean graph has no admissible path to complete support.",
                },
                "rows": rows,
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    tex = [
        "% Auto-generated by work/analyze_failure_funnel.py.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Failure-funnel outcomes for gated MRV versus hybrid retrieval. "
        "Win/loss denote an increase/decrease in either full evidence or support "
        "recall; $\\Delta$SR is mean support-recall change.}",
        "\\label{tab:failure-funnel}",
        "\\small",
        "\\begin{tabular}{llrrrr}",
        "\\toprule",
        "Dataset & Initial/graph state & $n$ & Wins & Losses & $\\Delta$SR \\\\",
        "\\midrule",
    ]
    for index, row in enumerate(rows):
        if index and row["dataset"] != rows[index - 1]["dataset"]:
            tex.append("\\midrule")
        tex.append(
            f"{DISPLAY[row['dataset']]} & {DISPLAY[row['slice']]} & "
            f"{row['queries']} & {row['wins']} & {row['losses']} & "
            f"{row['mean_support_recall_delta']:+.3f} \\\\"
        )
    tex.extend(["\\bottomrule", "\\end{tabular}", "\\end{table}", ""])
    args.tex_output.parent.mkdir(parents=True, exist_ok=True)
    args.tex_output.write_text("\n".join(tex), encoding="utf-8")
    print(json.dumps({"rows": len(rows), "queries": len(source)}, indent=2))


if __name__ == "__main__":
    main()
