from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from statistics import mean, stdev


DATASETS = ("hotpot", "2wiki", "musique")
DISPLAY = {
    "hotpot": "HotpotQA",
    "2wiki": "2WikiMultiHopQA",
    "musique": "MuSiQue",
}
PRIMARY_EMBEDDING = "qwen3-embedding_0.6b"
SECONDARY_EMBEDDING = "bge-m3_latest"
SEEDS = (101, 202, 303)
ROBUSTNESS_CONDITIONS = (
    "dropout_10",
    "dropout_25",
    "dropout_50",
    "false_edges_10",
    "false_edges_25",
    "false_edges_50",
    "mixed_25_25",
)


def tex_number(value: float | None, digits: int = 3) -> str:
    return "--" if value is None else f"{float(value):.{digits}f}"


def unit_score(value: float | None) -> float | None:
    """Normalize official scorer output to the [0, 1] interval."""
    if value is None:
        return None
    score = float(value)
    return score / 100.0 if score > 1.0 else score


def load_json(path: Path) -> dict | None:
    return (
        json.loads(path.read_text(encoding="utf-8"))
        if path.exists()
        else None
    )


def load_multiseed_robustness(path: Path) -> dict[tuple[str, str], dict]:
    if not path.exists():
        return {}
    with path.open(encoding="utf-8", newline="") as handle:
        return {
            (row["dataset"], row["condition"]): row
            for row in csv.DictReader(handle)
            if row["policy"] == "mrv_gated"
        }


def robustness_score(row: dict | None) -> str:
    if row is None:
        return "--"
    average = float(row["full_evidence_mean"])
    spread = float(row["full_evidence_std"])
    seeds = int(row["seeds"])
    if seeds <= 1:
        return f"{average:.3f}"
    return f"{average:.3f} $\\pm$ {spread:.3f}"


def summary_path(
    root: Path, dataset: str, embedding: str, seed: int = 101
) -> Path:
    return root / dataset / embedding / f"seed_{seed}" / "summary.json"


def mean_std(values: list[float]) -> str:
    if not values:
        return "--"
    spread = stdev(values) if len(values) > 1 else 0.0
    return f"{mean(values):.3f} $\\pm$ {spread:.3f}"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default="outputs/final_v1")
    parser.add_argument(
        "--reader-root", default="outputs/final_v1_reader_full"
    )
    parser.add_argument(
        "--reader-summary",
        default="outputs/final_v1/analysis/reader_full_summary.json",
    )
    parser.add_argument(
        "--robustness-root", default="outputs/final_v1_robustness"
    )
    parser.add_argument(
        "--robustness-aggregate",
        default="outputs/final_v1/analysis/robustness_multiseed_metrics.csv",
    )
    parser.add_argument(
        "--published-baseline-root",
        default="outputs/published_baselines",
    )
    parser.add_argument(
        "--output",
        default="outputs/graph_rescue_article/generated_results.tex",
    )
    args = parser.parse_args()
    root = Path(args.root)
    reader_root = Path(args.reader_root)
    reader_summary_payload = load_json(Path(args.reader_summary)) or {}
    reader_inference = {
        result["dataset"]: result
        for result in reader_summary_payload.get("results", [])
    }
    robustness_root = Path(args.robustness_root)
    multiseed_robustness = load_multiseed_robustness(
        Path(args.robustness_aggregate)
    )
    published_baseline_root = Path(args.published_baseline_root)
    readers = {
        dataset: load_json(
            reader_root / dataset / "seed_101" / "reader_analysis.json"
        )
        for dataset in DATASETS
    }
    reader_sizes = {
        int(reader["size"])
        for reader in readers.values()
        if reader is not None
    }
    if len(readers) == sum(reader is not None for reader in readers.values()):
        reader_scope = (
            f"the fixed {reader_sizes.pop():,}-query evaluation split"
            if len(reader_sizes) == 1
            else "the fixed evaluation splits"
        )
    else:
        reader_scope = "the available fixed evaluation splits"
    lines = [
        "% Auto-generated by work/generate_paper_assets.py.",
        "% Do not edit numeric values by hand.",
        r"\newcommand{\ResultStatus}{final experimental snapshot}",
        "",
        r"\begin{table*}[t]",
        r"\centering",
        r"\caption{Primary-seed retrieval results on the pooled-corpus protocol. "
        r"FE is full supporting-evidence retrieval; SR is mean support recall. "
        r"The oracle is a non-deployable graph-reachability upper bound.}",
        r"\label{tab:main-retrieval}",
        r"\small",
        r"\begin{tabular}{lrrrrrrr}",
        r"\toprule",
        r"Dataset & Hybrid FE & Gated FE & $\Delta$ FE & 95\% CI & "
        r"Hybrid SR & Gated SR & Oracle FE \\",
        r"\midrule",
    ]
    available_datasets = 0
    for dataset in DATASETS:
        summary = load_json(
            summary_path(root, dataset, PRIMARY_EMBEDDING)
        )
        if summary is None:
            lines.append(
                f"{DISPLAY[dataset]} & -- & -- & -- & [--, --] & "
                r"-- & -- & -- \\"
            )
            continue
        available_datasets += 1
        aggregate = summary["aggregate"]
        comparison = summary["comparisons"][
            "mrv_gated_vs_hybrid_full_evidence"
        ]
        lines.append(
            f"{DISPLAY[dataset]} & "
            f"{tex_number(aggregate['hybrid']['full_evidence'])} & "
            f"{tex_number(aggregate['mrv_gated']['full_evidence'])} & "
            f"{tex_number(comparison['difference'])} & "
            f"[{tex_number(comparison['ci95_low'])}, "
            f"{tex_number(comparison['ci95_high'])}] & "
            f"{tex_number(aggregate['hybrid']['support_recall'])} & "
            f"{tex_number(aggregate['mrv_gated']['support_recall'])} & "
            f"{tex_number(aggregate.get('oracle_upper_bound', {}).get('full_evidence'))} "
            r"\\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table*}",
            "",
            r"\begin{table*}[t]",
            r"\centering",
            r"\caption{Equal-budget comparison with an independent "
            r"KG$^2$RAG-style adaptation at seed 101. This is not an exact "
            r"reproduction of the published system: its triplet KG and "
            r"FlagReranker are replaced by our passage/entity graph and "
            r"shared semantic scorer. Deltas are against the adaptation.}",
            r"\label{tab:published-baseline}",
            r"\small",
            r"\begin{tabular}{lrrrrrr}",
            r"\toprule",
            r"Dataset & Hybrid FE & KG$^2$-style FE & Gated FE & "
            r"KG$^2$--Hybrid & Gated--KG$^2$ & KG$^2$ actions \\",
            r"\midrule",
        ]
    )
    for dataset in DATASETS:
        primary = load_json(
            summary_path(root, dataset, PRIMARY_EMBEDDING)
        )
        published = load_json(
            published_baseline_root
            / dataset
            / "kg2rag_style_qwen_seed101"
            / "summary.json"
        )
        if primary is None or published is None:
            lines.append(
                f"{DISPLAY[dataset]} & -- & -- & -- & -- & -- & -- \\\\"
            )
            continue
        hybrid = primary["aggregate"]["hybrid"]["full_evidence"]
        gated = primary["aggregate"]["mrv_gated"]["full_evidence"]
        style = published["aggregate"][
            "kg2rag_style_equal_budget"
        ]["full_evidence"]
        actions = published["aggregate"][
            "kg2rag_style_equal_budget"
        ]["graph_actions"]
        lines.append(
            f"{DISPLAY[dataset]} & {tex_number(hybrid)} & "
            f"{tex_number(style)} & {tex_number(gated)} & "
            f"{tex_number(style - hybrid)} & "
            f"{tex_number(gated - style)} & "
            f"{tex_number(actions, 2)} \\\\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table*}",
            "",
            r"\begin{table}[t]",
            r"\centering",
            r"\caption{Gate calibration and graph-use cost for the primary run.}",
            r"\label{tab:gate}",
            r"\small",
            r"\begin{tabular}{lrrrr}",
            r"\toprule",
            r"Dataset & AUROC & ECE & Gate positive & Actions \\",
            r"\midrule",
        ]
    )
    for dataset in DATASETS:
        summary = load_json(
            summary_path(root, dataset, PRIMARY_EMBEDDING)
        )
        if summary is None:
            lines.append(f"{DISPLAY[dataset]} & -- & -- & -- & -- \\\\")
            continue
        gate = summary["gate_metrics_by_stage"]["preflight"]
        actions = summary["aggregate"]["mrv_gated"]["graph_actions"]
        lines.append(
            f"{DISPLAY[dataset]} & {tex_number(gate['auroc'])} & "
            f"{tex_number(gate['ece'])} & "
            f"{tex_number(gate['predicted_positive_rate'])} & "
            f"{tex_number(actions, 2)} \\\\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}",
            "",
            r"\begin{table*}[t]",
            r"\centering",
            r"\caption{Representation sensitivity at seed 101. "
            r"All values are full-evidence rates; $\Delta$ compares gated "
            r"MRV with the embedding-matched hybrid retriever.}",
            r"\label{tab:embedding}",
            r"\small",
            r"\begin{tabular}{lrrrrrr}",
            r"\toprule",
            r"Dataset & Qwen hybrid & Qwen gated & Qwen $\Delta$ & "
            r"BGE hybrid & BGE gated & BGE $\Delta$ \\",
            r"\midrule",
        ]
    )
    for dataset in DATASETS:
        values = []
        for embedding in (PRIMARY_EMBEDDING, SECONDARY_EMBEDDING):
            summary = load_json(
                summary_path(root, dataset, embedding)
            )
            if summary is None:
                values.extend([None, None, None])
                continue
            hybrid = summary["aggregate"]["hybrid"]["full_evidence"]
            gated = summary["aggregate"]["mrv_gated"]["full_evidence"]
            values.extend([hybrid, gated, gated - hybrid])
        lines.append(
            f"{DISPLAY[dataset]} & "
            + " & ".join(tex_number(value) for value in values)
            + r" \\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table*}",
            "",
            r"\begin{table}[t]",
            r"\centering",
            r"\caption{Training-seed sensitivity with Qwen3 Embedding.}",
            r"\label{tab:seeds}",
            r"\small",
            r"\begin{tabular}{lrrr}",
            r"\toprule",
            r"Dataset & Hybrid FE & Gated FE & Gated actions \\",
            r"\midrule",
        ]
    )
    for dataset in DATASETS:
        summaries = [
            load_json(
                summary_path(root, dataset, PRIMARY_EMBEDDING, seed)
            )
            for seed in SEEDS
        ]
        summaries = [summary for summary in summaries if summary]
        if not summaries:
            lines.append(f"{DISPLAY[dataset]} & -- & -- & -- \\\\")
            continue
        lines.append(
            f"{DISPLAY[dataset]} & "
            f"{mean_std([float(s['aggregate']['hybrid']['full_evidence']) for s in summaries])} & "
            f"{mean_std([float(s['aggregate']['mrv_gated']['full_evidence']) for s in summaries])} & "
            f"{mean_std([float(s['aggregate']['mrv_gated']['graph_actions']) for s in summaries])} "
            r"\\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}",
            "",
            r"\begin{table*}[t]",
            r"\centering",
            r"\caption{Graph-corruption dose--response for gated MRV "
            r"(full-evidence rate). D denotes edge dropout, F denotes "
            r"false-edge injection, and Mix is D25/F25. Where available, "
            r"cells report mean $\pm$ sample SD across corruption seeds; "
            r"models are trained on the clean graph.}",
            r"\label{tab:robustness}",
            r"\scriptsize",
            r"\resizebox{\textwidth}{!}{%",
            r"\begin{tabular}{lrrrrrrrr}",
            r"\toprule",
            r"Dataset & Clean & D10 & D25 & D50 & F10 & F25 & F50 & Mix \\",
            r"\midrule",
        ]
    )
    for dataset in DATASETS:
        clean_row = multiseed_robustness.get((dataset, "clean"))
        if clean_row:
            values = [robustness_score(clean_row)]
        else:
            clean = load_json(
                summary_path(root, dataset, PRIMARY_EMBEDDING)
            )
            values = [
                tex_number(
                    clean["aggregate"]["mrv_gated"]["full_evidence"]
                    if clean
                    else None
                )
            ]
        for condition in ROBUSTNESS_CONDITIONS:
            aggregate_row = multiseed_robustness.get(
                (dataset, condition)
            )
            if aggregate_row:
                values.append(robustness_score(aggregate_row))
            else:
                summary = load_json(
                    robustness_root
                    / dataset
                    / condition
                    / "summary.json"
                )
                values.append(
                    tex_number(
                        summary["aggregate"]["mrv_gated"]["full_evidence"]
                        if summary
                        else None
                    )
                )
        lines.append(
            f"{DISPLAY[dataset]} & "
            + " & ".join(values)
            + r" \\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"}",
            r"\end{table*}",
            "",
            r"\begin{table*}[t]",
            r"\centering",
            rf"\caption{{Qwen3-8B reader evaluation on {reader_scope}. "
            r"Values are from each dataset's official scorer. Bracketed "
            r"intervals are paired 95\% bootstrap confidence intervals.}",
            r"\label{tab:reader}",
            r"\scriptsize",
            r"\resizebox{\textwidth}{!}{%",
            r"\begin{tabular}{lrrrrrr}",
            r"\toprule",
            r"Dataset & Base Ans.\ F1 & Gated Ans.\ F1 & $\Delta$ Ans.\ F1 "
            r"[95\% CI] & Base Sup.\ F1 & Gated Sup.\ F1 & "
            r"$\Delta$ Sup.\ F1 [95\% CI] \\",
            r"\midrule",
        ]
    )
    for dataset in DATASETS:
        reader = readers[dataset]
        if reader is None:
            lines.append(
                f"{DISPLAY[dataset]} & -- & -- & -- & -- & -- & -- \\\\"
            )
            continue
        base = reader["official"]["hybrid"]["metrics"]
        gated = reader["official"]["mrv_gated"]["metrics"]
        if dataset == "hotpot":
            answer_key, support_key = "f1", "sp_f1"
        elif dataset == "2wiki":
            answer_key, support_key = "f1", "sp_f1"
        else:
            answer_key, support_key = "answer_f1", "support_f1"
        inference = reader_inference.get(dataset, {})
        answer_delta = inference.get("deltas", {}).get("answer_f1")
        support_delta = inference.get("deltas", {}).get("support_f1")

        def delta_ci(value: dict | None) -> str:
            if not value:
                return "--"
            return (
                f"{float(value['difference']):+.3f} "
                f"[{float(value['ci95_low']):+.3f}, "
                f"{float(value['ci95_high']):+.3f}]"
            )

        lines.append(
            f"{DISPLAY[dataset]} & "
            f"{tex_number(unit_score(base[answer_key]))} & "
            f"{tex_number(unit_score(gated[answer_key]))} & "
            f"{delta_ci(answer_delta)} & "
            f"{tex_number(unit_score(base[support_key]))} & "
            f"{tex_number(unit_score(gated[support_key]))} & "
            f"{delta_ci(support_delta)} \\\\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"}",
            r"\end{table*}",
            "",
            f"\\newcommand{{\\AvailableDatasetRuns}}{{{available_datasets}}}",
        ]
    )
    macro_names = {
        "hotpot": "HotpotDelta",
        "2wiki": "TwoWikiDelta",
        "musique": "MusiqueDelta",
    }
    for dataset, macro in macro_names.items():
        summary = load_json(
            summary_path(root, dataset, PRIMARY_EMBEDDING)
        )
        delta = (
            summary["aggregate"]["mrv_gated"]["full_evidence"]
            - summary["aggregate"]["hybrid"]["full_evidence"]
            if summary
            else None
        )
        lines.append(
            f"\\newcommand{{\\{macro}}}{{{tex_number(delta)}}}"
        )
    reader_macro_names = {
        "hotpot": "Hotpot",
        "2wiki": "TwoWiki",
        "musique": "Musique",
    }
    for dataset, macro in reader_macro_names.items():
        inference = reader_inference.get(dataset, {})
        for metric, suffix in (
            ("answer_f1", "ReaderAnswer"),
            ("support_f1", "ReaderSupport"),
        ):
            value = inference.get("deltas", {}).get(metric)
            if value:
                delta_value = f"{float(value['difference']):+.3f}"
                ci_value = (
                    f"[{float(value['ci95_low']):+.3f}, "
                    f"{float(value['ci95_high']):+.3f}]"
                )
            else:
                delta_value = "--"
                ci_value = "[--, --]"
            lines.append(
                f"\\newcommand{{\\{macro}{suffix}Delta}}{{{delta_value}}}"
            )
            lines.append(
                f"\\newcommand{{\\{macro}{suffix}CI}}{{{ci_value}}}"
            )
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        json.dumps(
            {
                "output": str(output),
                "available_primary_datasets": available_datasets,
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
